package View;

import Process.InterviewSchedule;
import Process.InterviewScheduleDao;
import Process.MessageDialog;
import java.util.List;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author acer
 */
public class RMSchedule extends javax.swing.JDialog {

    /**
     * Creates new form RMSchedule
     */
    private DefaultTableModel model;
    
    public RMSchedule(java.awt.Frame parent, boolean modal, int maITV) {
        super(parent, modal);
        initComponents();
        setResizable(false);
        setLocationRelativeTo(null);
        
        model = (DefaultTableModel) tblSCHEDULE.getModel();
        LoadData(maITV);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblSCHEDULE = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel1.setText("DANH SÁCH LỊCH PHỎNG VẤN");

        tblSCHEDULE.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        tblSCHEDULE.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Mã lịch phỏng vấn", "Ngày bắt đầu", "Ngày kết thúc", "Địa điểm", "Trạng thái", "Số lượng tối đa"
            }
        ));
        tblSCHEDULE.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblSCHEDULEMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblSCHEDULE);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 988, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(317, 317, 317))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 323, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(20, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tblSCHEDULEMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblSCHEDULEMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_tblSCHEDULEMouseClicked

    /**
     * @param args the command line arguments
     */
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblSCHEDULE;
    // End of variables declaration//GEN-END:variables

    private void LoadData(int maITV) {
        try {
            InterviewScheduleDao dao = new InterviewScheduleDao();
            List<InterviewSchedule> list = dao.findListByInterviewerNo(maITV);
            model.setRowCount(0);
            for (InterviewSchedule x : list) {
                String trangthai;
                if (x.getSTATUS() == 0) {
                    trangthai = "Chưa hoàn thành";
                } else {
                    trangthai = "Đã hoàn thành";
                }

                model.addRow(new Object[]{
                    x.getINTERVIEWSCHEDULENO(), x.getSTARTTIME(), x.getENDTIME(),
                    x.getLOCATION(), trangthai, x.getSLOT()});
            }
            model.fireTableDataChanged();
            tblSCHEDULE.setModel(model);
        } catch (Exception e) {
            MessageDialog.showErrorDialog(this, e.getMessage(), "Lỗi");
        }
    }
}
